INTERNET_ACCESS: true # Set to true to enable internet access
MAX_SEARCH_RESULTS: 2 # Set the maximum search results for internet access DONT SET TOO HIGH

ALLOW_DM: true # Set to true to allow direct messages
SMART_MENTION: true # Set to true to enable smart mention feature

GPT_MODEL: mixtral-8x7b # Model used for chat completion

MAX_HISTORY: 2000 # Set the maximum message history

PRESENCES_CHANGE_DELAY: 129 # Please note that the Presences Change Delay is measured in seconds. It is advisable not to set it too low, as doing so may result in your bot being rate-limited by Discord
AI_NSFW_CONTENT_FILTER: false # Enable NSFW AI detector to detect NSFW prompt on Imagine Command

LANGUAGE: en # Specify the language code (check 'lang' folder for valid codes)

INSTRUCTIONS: SolarDefault # Specify the instruction prompt to use (check 'instructions' folder for valid prompts)
# To add custom prompts, create a .txt file like 'custom.txt' in `instructions` folder and set INSTRUCTIONS as 'custom'

Discord: https://discord.com/invite/YNGQ9EPhGq
Github: Unavailable.

TRIGGER:
  - Solar
  - solar
  - mixtralofexperts
# Define the triggers that the bot should always respond to when in message

DISABLE_PRESENCE: false 
PRESENCES:
  - Listening to /help information
  - Currently in {guild_count} guilds
  - Maybe Try Saying Hi Solar?.
  - Who tf randombly changes my pfp?
# List of different presences to be used

OCR_MODEL_URLS:
  - "https://api-inference.huggingface.co/models/microsoft/trocr-base-printed"
  - "https://api-inference.huggingface.co/models/nlpconnect/vit-gpt2-image-captioning"
# List of URLs for OCR models

BLACKLIST_WORDS:
  - khddhjhj
  
# Blacklisted words for /Imagine command this is disabled if you enable AI_NSFW_CONTENT_FILTER
